name: Checkout New Branch

on:
  repository_dispatch:
    types: [trigger-workflow]

permissions: 
  contents: write

jobs:
    run-powershell-scripts:
        runs-on: windows-latest
        steps:
          - name: Checkout repository
            uses: actions/checkout@v2
        
          - name: Create new branch
            run: |
                git config --global user.email "kamboj.prjwl@outlook.com"
                git config --global user.name "kamboj-prjjwl"
                git checkout -b temp-branch-test
                git push origin temp-branch-test

