name: Checkout New Branch

on:
  pull_request:
    types: [closed]
    branches:
      - main

permissions: 
  contents: write

jobs:
  checkout_new_branch:
    if: github.event.pull_request.merged == true && startsWith(github.event.pull_request.head.ref, 'network-release')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Fetch API version 
        id: fetch_api_version 
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
          GITHUB_REPOSITORY: ${{ github.repository }} 
        run: |
              ./eng/scripts/Get-ApiVersion.ps1
        shell: pwsh

      - name: Create Swagger Release Branch
        env: 
          API_VERSION: ${{ steps.fetch_api_version.outputs.api_version }} 
        run: |
              ./eng/scripts/Create-NetworkReleaseBranchSwagger-PS.ps1
        shell: pwsh
