name: Checkout New Branch

on:
  pull_request:
    types: [closed]
    branches:
      - main

permissions: 
  contents: write

jobs:
  checkout_new_branch:
    if: github.event.pull_request.merged == true && startsWith(github.event.pull_request.head.ref, 'network-release')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Fetch API version 
        id: fetch_api_version 
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
          GITHUB_REPOSITORY: ${{ github.repository }} 
        run: |
              ./eng/scripts/Fetch-SwaggerAPIVersion.ps1 -GITHUB_TOKEN ${{ env.GITHUB_TOKEN }} -REPO ${{ env.REPO }} -PR_NUMBER ${{ env.PR_NUMBER }}  
        shell: pwsh

      - name: Create Swagger Release Branch
        env: 
          API_VERSION: ${{ steps.fetch_api_version.outputs.api_version }}        
        run: |
              ./eng/scripts/Create-NetworkReleaseBranchSwagger.ps1 -API_VERSION ${{ steps.fetch_api_version.outputs.api_version }}
        shell: pwsh

      - name: Create and add label to PR 
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
          REPO: ${{ github.repository }} 
          PR_NUMBER: ${{ github.event.pull_request.number }} 
          NEW_LABEL: "SWG_API_VER_${{ steps.fetch_api_version.outputs.api_version }}"
        
        run: |
             ./eng/scripts/CreateAndAddLabel.ps1 -GITHUB_TOKEN ${{ env.GITHUB_TOKEN }} -REPO ${{ env.REPO }} -PR_NUMBER ${{ env.PR_NUMBER }} -NEW_LABEL ${{ env.NEW_LABEL }}
        shell: pwsh